### PR TITLE
Remove prod.yml from VMaaS

### PR DESCRIPTION
**Pull request by tshihad**
Since VMaaS repo only runs acceptance test for VMaaS setup, I am deleting prod.yml from this repo. 
@CharlieBlain @eamonnotoole It will be much easier you to maintain the acceptance test configuration for prod from hpegl-terraform-provider repo.

### CODE REVIEW

**Review by gandharvas — APPROVED** [review]

**Comment by gandharvas** [comment]
Will wait for merge till @CharlieBlain confirms this movement

**Review by arunkumarviswanathan — APPROVED** [review]
LGTM

**Comment by eamonnotoole** [comment]
@tshihad @arunkumarviswanathan I'm a bit concerned about this PR.  We (the Vulcan team) cannot maintain acceptance test inputs for individual services.  Also acceptance tests need to be run against production-quality systems, not just against integration systems.  I think that we'll need to get our PO involved to come to some conclusion as to how we ensure that we can run VMaaS acceptance tests against production quality systems.

**Comment by tshihad** [comment]
Holding the PR until @eamonnotoole comes back

**Pull request closed without merging**
