### PR TITLE
Include IaC testing for cicd

### PR DESCRIPTION
**Pull request by mahesh-hpe**
This PR adds changes for dev acceptance testing workflow. Now user can run specific set of testcase for Dev testing. The terraform logs are attached as artifacts for further reference.
Additionally, CI CD workflow has been added to test all the dev acceptance test.

Note: Github actions doesn't allow any individual workflow to be longer than 6hrs, hence the testcases were broken down.

Test workflows:
https://github.com/HewlettPackard/hpegl-vmaas-terraform-resources/actions/runs/7276501128
https://github.com/HewlettPackard/hpegl-vmaas-terraform-resources/actions/runs/7284337277

### CODE REVIEW

**Comment by mahesh-hpe** [comment]
image

**Comment by mahesh-hpe** [comment]
https://rally1.rallydev.com/#/326152755668ud/iterationstatus?detail=/userstory/722236374529

**Review by manjunath-batakurki — DISMISSED** [review]

**Comment by mahesh-hpe** [comment]
Latest Test Run:
https://github.com/HewlettPackard/hpegl-vmaas-terraform-resources/actions/runs/7384661815

**Comment by mahesh-hpe** [comment]
Running Individual testcase: https://github.com/HewlettPackard/hpegl-vmaas-terraform-resources/actions/runs/7396848910/job/20122817431

Running all the testcase: https://github.com/HewlettPackard/hpegl-vmaas-terraform-resources/actions/runs/7396838905/job/20122785932

**Comment by mahesh-hpe** [comment]
Latest run with publish to teams:
https://github.com/HewlettPackard/hpegl-vmaas-terraform-resources/actions/runs/7406285701
image
image

**Review by sabhish — APPROVED** [review]
LGTM

**Pull request merged**
